version: "3.4"

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "kunstgalerij"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
  api:
    image: kunstgalerijapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5000:5000
      - 5001:5000
    depends_on:
      - db
